language: node_js
sudo: required
dist: trusty
node_js:
  - stable
  - '5'
  - '5.1'
  - '4'
  - '4.2'
  - '4.1'
  - '4.0'
script:
  - npm run build
after_script:
  - npm run coveralls

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

# For Chrome to work
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
